### ISSUE TITLE
Auto-generate camel case handle from name

### ISSUE THREAD

**Issue by Emkaytoo** [Emkaytoo/craft-json-snippets#6]
By default, the handles in Craft models can be left blank and will be generated by the CMS during import by converting the `name` to camel case. It would be super sweet if this package could do that too, just to be more explicit during upload, and to allow for customization as necessary.

**Comment by alexgleason** [comment]
This is not possible with the way that [atom/snippets](https://github.com/atom/snippets) works.

The snippet files are in JSON/CSON, which is purely a data format. You can't do anything programmatic from inside a JSON/CSON file, you can only process those formats from an external application.

In the case of snippets, the Atom snippets plugin loads these files, then does whatever it's going to do to them. More specifically, when you start typing, the snippets plugin searches your text against its store of snippets, and offers to generate code if you hit tab. In theory, if the snippets plugin had some sort of programming hooks, you could write code in your plugin to execute tasks on certain events. But as it stands, achieving the functionality you want would require either 1) implementing hooks on the atom/snippets package, or 2) forking the atom/snippets package, hacking it, and using the modified version in this app.

Both would be difficult, and option 1 is better.

**Comment by Emkaytoo** [comment]
Not worth it. Closing.
